In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("retrieval_results.csv")

In [3]:
df

,query,role,retrieved_questions,similarity_score,precision@5,recall@5,mrr,f1
0,Tell me about a time you had to learn somethin...,Common,Describe a time when you identified and resolv...,0.635860,1.0,1.0,1.0,1.000000
1,Describe a time you handled a difficult situat...,Common,Describe a time when you identified and resolv...,0.711928,1.0,1.0,1.0,1.000000
2,Where do you see yourself in 5 years?,Common,Imagine you're working on an ML model for pred...,0.498966,0.4,1.0,0.5,0.571429
3,Tell me about a conflict you had with a cowork...,Common,Scenario: You're working on a critical project...,0.707847,1.0,1.0,1.0,1.000000
4,What skills do you hope to develop in your nex...,Common,Imagine you've been tasked with onboarding a n...,0.638675,0.8,1.0,1.0,0.888889
5,What's the most significant change you've had ...,Common,Given that our company is in the process of mi...,0.615393,1.0,1.0,1.0,1.000000
6,How does this role fit into your career path?,Common,Given a Sales / Solutions Engineer position at...,0.597792,0.6,1.0,1.0,0.750000
7,Tell me about a time you worked well within a ...,Common,Describe a situation where you had to collabor...,0.697556,1.0,1.0,1.0,1.000000
8,What are your expectations from leadership in ...,Common,Imagine a situation where the Quality Assuranc...,0.628693,1.0,1.0,1.0,1.000000
9,What motivates you to come to work every day?,Common,Imagine your team is building a new machine le...,0.569598,1.0,1.0,1.0,1.000000
10,How do you motivate others in a leadership role?,Common,Scenario: You're working on a mission-critical...,0.616476,1.0,1.0,1.0,1.000000
11,What tools or methods help you stay organized?,Common,Given a complex user interface for managing wa...,0.636495,1.0,1.0,1.0,1.000000
12,How do you build trust with new teammates?,Common,You're working on a project to develop an auto...,0.635711,1.0,1.0,1.0,1.000000
13,Describe a time you felt out of place in a wor...,Common,Describe a time when you had to balance user e...,0.601130,1.0,1.0,1.0,1.000000
14,Do you prefer working independently or in team...,Common,Describe a situation where you had to collabor...,0.647045,0.8,1.0,1.0,0.888889
15,Describe a time you led a project or team.,Common,Describe a situation where you had to collabor...,0.707368,1.0,1.0,1.0,1.000000
16,How do you delegate tasks effectively?,Common,Scenario: You've been brought on as a Scrum Ma...,0.673398,0.8,1.0,1.0,0.888889
17,How do you align with our company values?,Common,You're working on a high-priority integration ...,0.653939,1.0,1.0,1.0,1.000000
18,Why do you want to work at our company?,Common,"As our Embedded Systems Developer, you're work...",0.630768,1.0,1.0,1.0,1.000000
19,What makes a good leader in your opinion?,Common,You're leading a team responsible for maintain...,0.576433,1.0,1.0,1.0,1.000000
20,What are your long-term career aspirations?,Common,You're working on a critical proposal for a ma...,0.552730,1.0,1.0,1.0,1.000000
21,Describe your ideal workday.,Common,Given a tight deadline to deliver the latest f...,0.574593,0.6,1.0,1.0,0.750000
22,How do you deal with feedback that you disagre...,Common,Scenario: Your team is working on a critical f...,0.678690,1.0,1.0,1.0,1.000000
23,What role do you usually play in group settings?,Common,"During our recent migration to AWS, we encount...",0.553281,0.8,1.0,1.0,0.888889
24,What would you do if you disagreed with your m...,Common,Scenario: You're working on a critical project...,0.657971,1.0,1.0,1.0,1.000000
25,Tell me about a time you were highly motivated...,Common,Describe a time when you encountered an unexpe...,0.638549,1.0,1.0,1.0,1.000000
26,How do you contribute to a positive team envir...,Common,Given a tight deadline to deliver the latest f...,0.691738,1.0,1.0,1.0,1.000000
27,What drives your passion for this field?,Common,Given that our Cybersecurity company is develo...,0.579191,1.0,1.0,1.0,1.000000
28,How do you react to sudden changes in priorities?,Common,You're leading the redesign of our mobile app'...,0.632156,1.0,1.0,1.0,1.000000
29,How do you respond when a teammate isn't pulli...,Common,You're leading the development of a critical m...,0.639566,0.8,1.0,1.0,0.888889
30,Tell me about a time you mentored someone.,Common,Describe a time when you discovered a critical...,0.608940,1.0,1.0,1.0,1.000000
31,How do you ensure productivity when working re...,Common,Given a tight deadline to deliver the latest f...,0.678118,1.0,1.0,1.0,1.000000
32,How do you stay motivated during repetitive ta...,Common,You're leading a team tasked with implementing...,0.602529,1.0,1.0,1.0,1.000000
33,How do you organize and prioritize your daily ...,Common,Imagine our FoodTech app is launching a new fe...,0.659073,1.0,1.0,1.0,1.000000
34,What type of company culture do you thrive in?,Common,Given that we're a FoodTech company focused on...,0.593130,1.0,1.0,1.0,1.000000
35,How do you handle disagreements within a team?,Common,You've been tasked with resolving a conflict b...,0.744480,1.0,1.0,1.0,1.000000
36,Describe a project where teamwork was essentia...,Common,Describe a situation where you had to collabor...,0.738032,1.0,1.0,1.0,1.000000
37,Describe a time you failed and what you learne...,Common,Describe a time when you encountered an unexpe...,0.636723,1.0,1.0,1.0,1.000000
38,How do you stay updated with industry trends?,Common,You're working on a critical feature for our n...,0.623990,1.0,1.0,1.0,1.000000
39,What kind of growth opportunities are you look...,Common,Given our upcoming release of a new cross-plat...,0.628442,1.0,1.0,1.0,1.000000

In [4]:
generation_df = pd.read_csv("generation_results.csv")

In [5]:
generation_df

,query,reference_answer,generated_answer,exact_match,bleu,rouge1,rouge2,rougeL,token_f1
0,Tell me about a time you had to learn somethin...,I'm always eager to learn and embrace change a...,I recall a situation where I was tasked with i...,0,0.004621,0.165138,0.027778,0.091743,0.165138
1,Describe a time you handled a difficult situat...,"When faced with conflict, I approach it calmly...",I recall a challenging incident where I had to...,0,0.001692,0.064865,0.000000,0.054054,0.064865
2,Where do you see yourself in 5 years?,My long-term goal is to grow into a senior rol...,"In five years, I envision myself as a leading ...",0,0.023369,0.160804,0.071066,0.120603,0.140704
3,Tell me about a conflict you had with a cowork...,"When faced with conflict, I approach it calmly...",I recall a situation where I was working on a ...,0,0.002225,0.091228,0.014134,0.063158,0.084211
4,What skills do you hope to develop in your nex...,My long-term goal is to grow into a senior rol...,I'm eager to develop a range of skills that wi...,0,0.009762,0.153846,0.025974,0.089744,0.153846
5,What's the most significant change you've had ...,I'm always eager to learn and embrace change a...,I'd treat this as a case of balancing competin...,0,0.004840,0.137931,0.023256,0.103448,0.126437
6,How does this role fit into your career path?,My long-term goal is to grow into a senior rol...,This role aligns with my long-term career goal...,0,0.009096,0.163934,0.033149,0.131148,0.142077
7,Tell me about a time you worked well within a ...,I believe communication and mutual respect are...,I've had experience working collaboratively wi...,0,0.007143,0.105820,0.021390,0.095238,0.105820
8,What are your expectations from leadership in ...,"I thrive in collaborative, transparent environ...",I expect leadership in a company to be transpa...,0,0.001085,0.059259,0.007463,0.044444,0.044444
9,What motivates you to come to work every day?,I'm motivated by challenges and the opportunit...,I'm motivated by a desire to deliver high-qual...,0,0.044085,0.259740,0.080000,0.233766,0.233766
10,How do you motivate others in a leadership role?,I lead by example and encourage open communica...,I motivate others by setting clear expectation...,0,0.007257,0.217822,0.040404,0.198020,0.198020
11,What tools or methods help you stay organized?,I follow a structured workflow and use tools l...,I use various tools and methods to stay organi...,0,0.003634,0.135593,0.011429,0.090395,0.124294
12,How do you build trust with new teammates?,I believe communication and mutual respect are...,I believe building trust with new teammates st...,0,0.002578,0.093617,0.008584,0.085106,0.076596
13,Describe a time you felt out of place in a wor...,"I thrive in collaborative, transparent environ...",I recall a situation where I joined a new team...,0,0.001551,0.064865,0.000000,0.043243,0.054054
14,Do you prefer working independently or in team...,I follow a structured workflow and use tools l...,I believe that both independent work and team ...,0,0.001500,0.058824,0.000000,0.058824,0.058824
15,Describe a time you led a project or team.,I lead by example and encourage open communica...,I recall leading a project that involved devel...,0,0.003777,0.136364,0.011494,0.102273,0.125000
16,How do you delegate tasks effectively?,I lead by example and encourage open communica...,"To delegate tasks effectively, I would follow ...",0,0.001554,0.083333,0.000000,0.064815,0.074074
17,How do you align with our company values?,"I thrive in collaborative, transparent environ...",I strive to embody the core principles of Defe...,0,0.002151,0.135135,0.000000,0.081081,0.094595
18,Why do you want to work at our company?,I'm motivated by challenges and the opportunit...,I'm excited about the opportunity to join your...,0,0.008162,0.095238,0.036145,0.083333,0.095238
19,What makes a good leader in your opinion?,I lead by example and encourage open communica...,A good leader prioritizes making informed deci...,0,0.003787,0.164948,0.000000,0.103093,0.123711
20,What are your long-term career aspirations?,My long-term goal is to grow into a senior rol...,I'm excited about the opportunity to continue ...,0,0.012360,0.183784,0.054645,0.118919,0.151351
21,Describe your ideal workday.,I follow a structured workflow and use tools l...,My ideal workday would be one that balances pr...,0,0.001459,0.037736,0.005420,0.032345,0.037736
22,How do you deal with feedback that you disagre...,"When faced with conflict, I approach it calmly...",I approach feedback that I disagree with in a ...,0,0.007426,0.118812,0.040000,0.089109,0.108911
23,What role do you usually play in group settings?,I believe communication and mutual respect are...,"I'm an active listener, often taking on a faci...",0,0.004255,0.164706,0.000000,0.117647,0.117647
24,What would you do if you disagreed with your m...,"When faced with conflict, I approach it calmly...",I'd address the disagreement directly and priv...,0,0.006978,0.222222,0.020619,0.141414,0.181818
25,Tell me about a time you were highly motivated...,I'm motivated by challenges and the opportunit...,I recall a situation where I was tasked with o...,0,0.005490,0.072289,0.024291,0.056225,0.072289
26,How do you contribute to a positive team envir...,"I thrive in collaborative, transparent environ...",I believe that contributing to a positive team...,0,0.001498,0.062827,0.000000,0.041885,0.052356
27,What drives your passion for this field?,I'm motivated by challenges and the opportunit...,I'm driven by a desire to solve complex proble...,0,0.003714,0.103896,0.013158,0.090909,0.090909
28,How do you react to sudden changes in priorities?,I'm always eager to learn and embrace change a...,I react to sudden changes in priorities by rem...,0,0.004018,0.134078,0.011299,0.111732,0.134078
29,How do you respond when a teammate isn't pulli...,"When faced with conflict, I approach it calmly...",I'd address the issue directly and privately w...,0,0.003568,0.114943,0.034884,0.091954,0.103448
30,Tell me about a time you mentored someone.,I lead by example and encourage open communica...,I recall a situation where I was tasked with m...,0,0.001545,0.107438,0.000000,0.082645,0.107438
31,How do you ensure productivity when working re...,I follow a structured workflow and use tools l...,"To ensure productivity while working remotely,...",0,0.003944,0.111111,0.014085,0.097222,0.083333
32,How do you stay motivated during repetitive ta...,I'm motivated by challenges and the opportunit...,I'd treat this as a case of balancing competin...,0,0.002102,0.084507,0.000000,0.070423,0.070423
33,How do you organize and prioritize your daily ...,I follow a structured workflow and use tools l...,I prioritize my tasks based on business impact...,0,0.015085,0.077670,0.039216,0.077670,0.077670
34,What type of company culture do you thrive in?,"I thrive in collaborative, transparent environ...",I thrive in a company culture that values tran...,0,0.011695,0.194175,0.059406,0.155340,0.116505
35,How do you handle disagreements within a team?,I believe communication and mutual respect are...,I address disagreements directly and privately...,0,0.002976,0.074766,0.000000,0.074766,0.074766
36,Describe a project where teamwork was essentia...,I believe communication and mutual respect are...,I recall working on a project that required se...,0,0.004066,0.122066,0.028436,0.103286,0.112676
37,Describe a time you failed and what you learne...,I'm always eager to learn and embrace change a...,I recall a situation where I was tasked with i...,0,0.004070,0.135021,0.025532,0.084388,0.135021
38,How do you stay updated with industry trends?,I'm always eager to learn and embrace change a...,I stay updated with industry trends through va...,0,0.004069,0.150943,0.000000,0.094340,0.150943
39,What kind of growth opportunities are you look...,My long-term goal is to grow into a senior rol...,I'm looking for growth opportunities that alig...,0,0.012274,0.195804,0.042553,0.097902,0.181818